package br.fiap.form;

import br.fiap.dao.DAO;
import br.fiap.laboratorio.Laboratorio;
import br.fiap.ocorrencia.Ocorrencia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author soonicz
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupProblema = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtChamado = new javax.swing.JTextField();
        cmbComputador = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        bntSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnCadastrarLab = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        cmbLab = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número do chamado");

        jLabel2.setText("Laboratório");

        jLabel3.setText("Computador");

        jLabel4.setText("Problema");

        cmbComputador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        groupProblema.add(jCheckBox1);
        jCheckBox1.setText("Hardware");

        groupProblema.add(jCheckBox2);
        jCheckBox2.setText("Software");

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnCadastrarLab.setText("Cadastrar Laboratório");
        btnCadastrarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLabActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        cmbLab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">> Selecione um Lab <<" }));
        cmbLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbLabMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChamado)
                            .addComponent(cmbComputador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2))
                            .addComponent(cmbLab, 0, 191, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarLab)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalizar)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbComputador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnCadastrarLab)
                    .addComponent(btnFinalizar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Finaliza o programa
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    //Adquire as variaveis, valida e cria um objeto Ocorrencia
    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        int chamado = Integer.parseInt(txtChamado.getText());
        boolean conseguiu;
        String lab = (String) cmbLab.getSelectedItem();
        String comp = (String) cmbComputador.getSelectedItem();
        String problema = "";
        if (jCheckBox1.isSelected()) {
            problema = "Hardware";
        }
        if (jCheckBox2.isSelected()) {
            problema = "Software";
        }
        if (lab.equals("") || problema.equals("") || lab.equalsIgnoreCase(">> Selecione um Lab <<")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!!");
        } else {

            DAO dao = new DAO();
            Ocorrencia ocorrencia = new Ocorrencia(chamado, lab, comp, problema);
            conseguiu = dao.inserirOcorrencia(ocorrencia);
            if (conseguiu) {
                JOptionPane.showMessageDialog(this, "A ocorrencia foi registrada no banco!");
            }
        }
    }//GEN-LAST:event_bntSalvarActionPerformed

    //Chama o Form2 para cadastrar um novo Laboratorio
    private void btnCadastrarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLabActionPerformed
        dispose();
        new Form2().setVisible(true);
    }//GEN-LAST:event_btnCadastrarLabActionPerformed

    /*
     *  Adquire o nº do chamado
     *  Chama o DAO.pesquisarOcorrencia
     *  Seta os outros campos com os valores encontrados no banco
     */
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int chamado = Integer.parseInt(txtChamado.getText());
        DAO dao = new DAO();
        Ocorrencia aux;
        aux = dao.pesquisarOcorrencia(chamado);

        if (aux != null) {
            cmbLab.setSelectedItem(aux.getLab());
            cmbComputador.setSelectedItem(String.valueOf(aux.getComp()));
            if (aux.getProblema().equals("Hardware")) {
                jCheckBox1.setSelected(true);
            } else {
                jCheckBox2.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possivel achar o chamado no banco!");
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    //Atualiza a ComboBox com os laboratorios já cadastrados
    private void cmbLabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbLabMousePressed
        atualizarLista();
    }//GEN-LAST:event_cmbLabMousePressed

    /*
     *  Chama o DAO.pesquisarLaboratorio
     *  Remove e atualiza o ComboBox com os dados da lista encontrados no banco
     */
    public void atualizarLista() {
        cmbLab.removeAllItems();
        cmbLab.addItem(">> Selecione um Lab <<");
        DAO dao = new DAO();
        ArrayList<Laboratorio> labList = dao.pesquisarLaboratorio();
        String aux = null;
        for (int i = 0; i < labList.size(); i++) {
            aux = labList.get(i).getLab();
            cmbLab.addItem(aux);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // select Look and Feel
            //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");  
            //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");    
            //UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");  
            //UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");  
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel"); 

            // start application
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnCadastrarLab;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbComputador;
    private javax.swing.JComboBox<String> cmbLab;
    private javax.swing.ButtonGroup groupProblema;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtChamado;
    // End of variables declaration//GEN-END:variables

}
